version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: FileProcessor  
        Alias: live           
        CurrentVersion: 1     
        TargetVersion: 2     
